### ISSUE TITLE
Dependency incorrect for TNHTweaker 1.6.7

### ISSUE THREAD

**Issue by O-Deka-K** [Deli-Collective/DeliCounter.Database#116]
Tools/TNHTweaker/1.6.7.json was just added, replacing version 1.6.6. Not only is Devyndamonster-TakeAndHoldTweaker.zip not packaged with the files in Deli/mods (so it extracts all files to the H3VR root instead), but it also has a dependency on Deli 0.4.1. The 1.6.7.json says that the dependency is for Deli 0.3.0, but the manifest.json in TNHTweaker says 0.4.1. The database hasn't made Deli 0.4.1 or higher available, so TNHTweaker 1.6.7 doesn't load.

[LogOutput.log](https://github.com/Deli-Collective/DeliCounter.Database/files/6853008/LogOutput.log)

**Comment by nrgill28** [comment]
TNHT has been reverted in the database to 1.6.6 and will no longer receive updates. Due to BoneTome shutting down, Deli Counter will not be available for much longer and I would recommend switching to [r2modman](https://h3vr.thunderstore.io/package/ebkr/r2modman/) which pulls mods from Thunderstore instead.
