### ISSUE TITLE
Why have the version number both in the file name and as a entry in the file?

### ISSUE THREAD

**Issue by Aegarain** [Deli-Collective/DeliCounter.Database#17]
Just wondering. If they aren't equal, what will happen?

**Comment by nrgill28** [comment]
The filename actually doesn't matter and really the only reason they are the version number is so that  it's easier to locate the correct file for mods which do have multiple versions available. For mods on BoneTome where it's not possible to have multiple versions anyway then yeah the filename is completely unused.
