### ISSUE TITLE
Mark mods as incompatible

### ISSUE THREAD

**Issue by Aegarain** [Deli-Collective/DeliCounter.Database#30]
Is there a way to mark mods as incompatible, for example for two skin mods that edit the same weapon?

**Comment by nrgill28** [comment]
There is, but it's not in a release build yet. I have already added two mods which require that since you can't have two TNH Announcers installed: [Lois D Tall](https://github.com/Deli-Collective/DeliCounter.Database/blob/main/AssetReplacements/LoisDTall/1.0.0.json) and [Kamiya](https://github.com/Deli-Collective/DeliCounter.Database/blob/main/AssetReplacements/Kamiya/1.0.0.json)

I do want to put out a new release soon, though I'm deciding if I want to add some other stuff in first before I do and bump Deli Counter to v0.2.

**Comment by Aegarain** [comment]
Cool, thanks for letting me know

**Comment by nrgill28** [comment]
If you'd like to test it out before I do a release, you can download the latest automatic build from this page: https://github.com/Deli-Collective/DeliCounter/actions. Just click on the latest workflow run and download the `DeliCounter` artifact
